### ISSUE TITLE
[BUG]'Watch Now' missing from Smart Play popup

### ISSUE THREAD

**Issue by Dealz-416LS** [SerpentDrago/SerenTheme-SerenMod-Full#12] opened 2021-03-23 22:30 UTC
'Watch Now' button is missing from the smart play popup.

Only showing 'Close' button.

![Kodi_20210323_221744](https://user-images.githubusercontent.com/54026944/112226619-476e7800-8c26-11eb-9e72-ae9e1f6f0cb5.png)

[kodi.log](https://github.com/SerpentDrago/SerenTheme-SerenMod-Full/files/6193079/kodi.log)

Kodi: 19.0 Matrix
Seren: 2.0.17+Matrix. 1
Auramod: 1.0.3.3
SerenTheme-SerenMod-Full: 0.0.7

**Comment by SerpentDrago** [comment] 2021-03-24 02:25
This theme Is not compatible with seren 2.0 .

you can TRY the Serenstockmod branch instead but i've not updated that in quite awhile also

**Comment by SerpentDrago** [comment] 2021-03-24 02:29
I would not recommend this branch/theme for seren 2.0 you are missing many buttons in SS screen and such that seren 2.0 added . This theme is abandoned .

You can TRY the serenstockmod branch (read the readme in that branch) https://github.com/SerpentDrago/SerenTheme-SerenMod-Full/tree/serenstockmod

**Comment by Dealz-416LS** [comment] 2021-03-24 02:46
I honestly didn't even know there was other branches.

I understand the new buttons (Play, View Uncached and Download) aren't integrated directly into the theme on the SS screen but I can still access them there just fine via the context menu if I need them.

I thought this theme was good to use as it got fixes recently via PRs.

**Comment by SerpentDrago** [comment] 2021-03-24 13:08
yeh i thought it was but must have some bugs still , your welcome to try to fix it :) just mess around its to to hard for a simple theme .

off course that bug your talking about could be caused by the include it uses in auramod / AH . + matrix 19 .. 

as you know matrix 19 has broken lots of weird shit

**Comment by Dealz-416LS** [comment] 2021-03-24 14:15
I've brought the issue to the attention of @inb4after following some testing the issue was found to be the `Minimum Seconds Left Before Showing Dialog` in Seren Playback settings, I had it set to 90 seconds which broke the 'Watch Now' button, inb4after advised i set it back to 30 seconds and the 'Watch Now' button worked again.

Turns out the theme was capped at 59 seconds but Seren goes up to 180 seconds, so anything higher than 59 seconds broke the 'Watch Now' button.

**Comment by SerpentDrago** [comment] 2021-03-24 15:05
Thanks ! PR merged !

**Closed as completed** 2021-03-24 15:04 UTC

**Comment by SerpentDrago** [comment] 2021-03-24 15:09
@Dealz-416LS  you may want to check out his full fork of this > https://github.com/inb4after/SerenTheme-SerenMod-Full

seems hes got a LOT of nice fix's

**Comment by Dealz-416LS** [comment] 2021-03-24 15:50
@SerpentDrago Thanks for letting me know, I didn't notice he had a fork. I'll check it out.
